import { NgModule } from "@angular/core";
import { 
  MatAutocompleteModule, 
  MatButtonModule, 
  MatButtonToggleModule, 
  MatCardModule, 
  MatCheckboxModule, 
  MatChipsModule, 
  MatDatepickerModule, 
  MatDialogModule, 
  MatExpansionModule, 
  MatGridListModule, 
  MatIconModule, 
  MatInputModule, 
  MatListModule, 
  MatMenuModule, 
  MatProgressBarModule, 
  MatProgressSpinnerModule, 
  MatRadioModule, 
  MatRippleModule, 
  MatSelectModule, 
  MatSidenavModule, 
  MatSlideToggleModule, 
  MatSliderModule, 
  MatSnackBarModule, 
  MatTabsModule, 
  MatToolbarModule, 
  MatTooltipModule, 
  MatNativeDateModule, 
  MatSortModule, 
  MatPaginatorModule 
} from '@angular/material';


@NgModule({
  declarations: [],
  imports: [],
  exports: [
    MatAutocompleteModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatSnackBarModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatNativeDateModule,
    MatSortModule,
    MatPaginatorModule
  ]
})
export class MaterialsModule { }